// const countrylist = {
//     NZ : "NZD",
//     CK : "NZD",
//     NU : "NZD",
//     PN : "NZD",
//     TK : "NZD",
//     AU : "AUD",
//     CX : "AUD",
//     CC : "AUD",
//     HM : "AUD",
//     KI : "AUD",
//     NR : "AUD",
//     NF : "AUD",
//     TV : "AUD",
//     AS : "EUR",
//     AD : "EUR",
//     AT : "EUR",
//     BE : "EUR",
//     FI : "EUR",
//     FR : "EUR",
//     GF : "EUR",
//     TF : "EUR",
//     DE : "EUR",
//     GR : "EUR",
//     GP : "EUR",
//     IE : "EUR",
//     IT : "EUR",
//     LU : "EUR",
//     MQ : "EUR",
//     YT : "EUR",
//     MC : "EUR",
//     NL : "EUR",
//     PT : "EUR",
//     RE : "EUR",
//     WS : "EUR",
//     SM : "EUR",
//     SI : "EUR",
//     ES : "EUR",
//     VA : "EUR",
//     GS : "GBP",
//     GB : "GBP",
//     JE : "GBP",
//     IO : "USD",
//     GU : "USD",
//     MH : "USD",
//     FM : "USD",
//     MP : "USD",
//     PW : "USD",
//     PR : "USD",
//     TC : "USD",
//     US : "USD",
//     UM : "USD",
//     VG : "USD",
//     VI : "USD",
//     HK : "HKD",
//     CA : "CAD",
//     JP : "JPY",
    
// };



